branches:
  only:
    - master
git:
  depth: 10

language: cpp

dist: xenial

os:
  - linux
  - osx

env:
  global:
    - APM_TEST_PACKAGES: linter intentions linter-ui-default busy-signal
  jobs:
    - ATOM_CHANNEL: stable
    - ATOM_CHANNEL: beta

addons:
  apt:
    packages:
      - build-essential
      - fakeroot
      - git
      - libgconf2-4
      - libsecret-1-dev

script: "curl -sL https://git.io/fji1w | sh"
