branches:
  only:
    - master
git:
  depth: 10

language: cpp

matrix:
  include:
    - os: osx
    - os: linux
      dist: xenial

addons:
  apt:
    packages:
      - build-essential
      - fakeroot
      - git
      - libgconf2-4
      - libsecret-1-dev

env:
- ATOM_CHANNEL=stable
- ATOM_CHANNEL=beta

script: "curl -sL https://git.io/fji1w | sh"
